### ISSUE TITLE
Allure reports does not workout a live server

### ISSUE THREAD

**Issue by anubajaj23** [Shelex/cypress-allure-plugin#116]
**Describe the bug**
I am trying to setup allure reports with azure devops. Plugin is installed successfully and able to generate allure reports but can not view the results without a live server. 

**To Reproduce**
1. Open downloaded allure reports/index.html in the browser
2. Reports are not coming, CORS origin is coming

**Expected behavior**
Should work without a server.

**Environment (please complete the following information):**
- Cypress version:                                6.5.0
- Browser - Chrome
- OS:                                                      Mac 

<img width="1683" alt="Screenshot 2022-01-24 at 3 33 49 PM" src="https://user-images.githubusercontent.com/51432815/150762340-04c8cb47-46a8-45d5-af3e-e083bfc15c38.png">

** Developer Tools Console Output **
<img width="1640" alt="Screenshot 2022-01-24 at 3 34 27 PM" src="https://user-images.githubusercontent.com/51432815/150762532-b00ce89b-1487-4cb6-ac19-e3578d7305dd.png">

------------------------------------------------------------------------------------------------->

**Comment by Shelex** [comment]
Hi @anubajaj23 
You are correct - allure report will not work without hosting, for example serving it with web-server, s3 with hosting enabled, github pages, locally you can do `allure open` or `allure serve`, etc.

That is because allure is not just html, but an app that loads content based on your json results.

I am sure Azure has options to host a report, for example [Azure Blob Storage](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-static-website).

**Comment by Shelex** [comment]
Closing as question is quite not related to plugin itself.
