### ISSUE TITLE
Screenshot is not attached after waiting for element fails

### ISSUE THREAD

**Issue by kamiloski88** [Shelex/cypress-allure-plugin#131]
**Describe the bug**
Screenshot is not attached after waiting for element fails.
When test fails on cy.get(this.notificationPopupMessage).should('have.text', message);
In report I get (without screenshot)
Timed out retrying after 15000ms: Expected to find element: `.ant-notification-notice-message`, but never found it.

Screenshot is not attached - missing screenshot (attachment) in allure-results folder.

**What I noticed - if I add .only to this test (it) then attachment is generated in allure-results and it is attached to report**

I think I know when problem appears - I use 'cypress-plugin-snapshots'. When I have multiple it(), and in first it test fails on compare screenshot and then next it() fails eg. because cant find element then eg (Timed out retrying after 15000ms: Expected to find element: `.ant-notification-notice-message`, but never found it.) then screenshot is not in report.
When I change order of tests (first it fails because cannot find element) and second test fails on compare screenshots then all screenshots are attached to repord and exists in allure-results.
Do you know what is wrong?

**Comment by Shelex** [comment]
The problem with `cypress-plugin-snapshots` is that it overrides `onAfterScreenshot` config not taking into account that there could be other listeners for such event in Cypress.
From cypress-allure-reporter side we already are using separate logic from `onAfterScreenshot` to handle attachments and this should not be an issue.

Moreover while checking sources I have also noted that latest update for `cypress-plugin-snapshots` was on 11 Aug 2020, it is based on cypress v4.5.0 and a lot of things have changed dramatically since that time. 
Also, there are a lot of issues doubting that plugin is maintained, according to issue https://github.com/meinaart/cypress-plugin-snapshots/issues/210 there are already alternatives available.
