### ISSUE TITLE
Cucumber-Keyword "Rule" Didn't Work

### ISSUE THREAD

**Issue by lopopnehuv** [Shelex/cypress-allure-plugin#149]
**Describe the bug**
Can't pass feature with "Rule"-keyword
<img width="284" alt="Screen Shot 2022-08-10 at 6 58 56 PM" src="https://user-images.githubusercontent.com/68075409/183956858-14d43260-8fcd-44bc-8524-8f4edba55dfc.png"> <img width="290" alt="Screen Shot 2022-08-10 at 7 02 22 PM" src="https://user-images.githubusercontent.com/68075409/183957829-0ae82b9c-4799-478b-a309-9b66e531de63.png">

**To Reproduce**
1. package.json like this
<img width="508" alt="Screen Shot 2022-08-10 at 6 54 38 PM" src="https://user-images.githubusercontent.com/68075409/183954949-cf5a8e5b-317e-4953-96e9-750dd3d86bd0.png">

2. cypress.config.ts like this:
<img width="592" alt="Screen Shot 2022-08-10 at 6 53 29 PM" src="https://user-images.githubusercontent.com/68075409/183954443-3cab2f54-d718-453d-ae3f-9213c1cbf3c0.png">

**Expected behavior**
Can pass feature with "Rule"-keyword

**Environment (please complete the following information):**
- Cypress version:                                10.4.0
- OS:                                                      Mac

** Developer Tools Console Output **
<img width="1238" alt="Screen Shot 2022-08-10 at 7 04 19 PM" src="https://user-images.githubusercontent.com/68075409/183958256-cffb1707-8c27-43fe-82a7-24c27000bcae.png">

**Additional context**
1. Can pass feature with "Rule"-keyword when deactivate cypress-allure-plugin

**Comment by Shelex** [comment]
Hi @lopopnehuv 
Support for "rule" keyword provided in v2.28.5
Could you please check it on your side?

**Comment by Shelex** [comment]
Hi @lopopnehuv 
Thanks for great report!

Let me visit each point:
> Scenario Overwrite (6 vs 12 results)
    Based on Scenario Name and Last Feature Launch

I am afraid we are facing here the core issue with Allure report itself. Allure treats test with same name - a same test, no matter whether the structure is different, or test is in separate file - if names are same, test is same. Like here - https://github.com/allure-framework/allure2/issues/1196 

I have an idea of some heuristical logic of checking the test names when writing allure-results. We can check suite structure, check filename, and in case there is already a test with same name - concatenate it with some counter, or details that are different, however, that feature is still in "mind palace". 

> Limited Tags
    Expectation: @featureTag, @ruleTag @scenarioTag
    Reality: @featureTag @scenarioTag

Sure, this should be addressed.

> If scenario doesn't have Rule - Suite becomes a Feature

I will revisit the cucumber docs about "Rule" keyword and its meaning, because I do not get what is the problem here and how we should treat "Rule" in terms of allure epic, feature, or story labels.

> Can You Add ENV for hideAfterEachHook / hideBeforeEachHook? :3 or something similar

If you mean just removing these steps when they are empty - I guess we don't need a flag for that, but just remove it.

**Comment by Shelex** [comment]
After additional checks on latest version I can see that issue with `If scenario doesn't have Rule - Suite becomes a Feature` is also gone, assuming fixed in terms of handling tags.

So closing this issue as all 3 items resolved and the first one is actually the way how allure work. An enhancement is planned, however that will be a completely separate issue.
