### ISSUE TITLE
It was not possible do use @issue or @tms using the last version of this plugin

### ISSUE THREAD

**Issue by Rogatto** [Shelex/cypress-allure-plugin#165]
**Describe the bug**

It was not possible to use @issue or @tms using the last version of this plugin, is it necessary to use cypress webpack to use those annotations?

**To Reproduce**

Just tried to use @issue and @tms but it didn't work and return:

at AllureInterface.link (webpack:///./node_modules/@shelex/allure-js-commons-browser/dist/src/Allure.js:34:0)
      at AllureInterface.issue (webpack:///./node_modules/@shelex/allure-js-commons-browser/dist/src/Allure.js:37:0)
      at ./cypress/e2e/cart-page-1/delete.product.using.api.spec.js (webpack:///./cypress/e2e/cart-page-1/delete.product.using.api.spec.js:8:7)
      at __webpack_require__ (webpack:///webpack/bootstrap:19:0)
      at 0 (http://localhost:3000/__cypress/tests?p=cypress/e2e/cart-page-1/delete.product.using.api.spec.js:269:18)
      at __webpack_require__ (webpack:///webpack/bootstrap:19:0)
      at eval (webpack:///webpack/bootstrap:83:0)
      at eval (http://localhost:3000/__cypress/tests?p=cypress/e2e/cart-page-1/delete.product.using.api.spec.js:87:10)
      at eval (<anonymous>)

**Expected behavior**

**Environment (please complete the following information):**
- Cypress version:                                #.##
- OS: Mac                                                     Windows | Mac | Linux (distro):

** Developer Tools Console Output **

at AllureInterface.link (webpack:///./node_modules/@shelex/allure-js-commons-browser/dist/src/Allure.js:34:0)
      at AllureInterface.issue (webpack:///./node_modules/@shelex/allure-js-commons-browser/dist/src/Allure.js:37:0)
      at ./cypress/e2e/cart-page-1/delete.product.using.api.spec.js (webpack:///./cypress/e2e/cart-page-1/delete.product.using.api.spec.js:8:7)
      at __webpack_require__ (webpack:///webpack/bootstrap:19:0)
      at 0 (http://localhost:3000/__cypress/tests?p=cypress/e2e/cart-page-1/delete.product.using.api.spec.js:269:18)
      at __webpack_require__ (webpack:///webpack/bootstrap:19:0)
      at eval (webpack:///webpack/bootstrap:83:0)
      at eval (http://localhost:3000/__cypress/tests?p=cypress/e2e/cart-page-1/delete.product.using.api.spec.js:87:10)
      at eval (<anonymous>)

**Additional context**

**Comment by Shelex** [comment]
Hi @Rogatto 
Could you please specify how do you use it? Other plugins, own functions?
Or just provide an example?

I have checked such variants in gherkin file in https://github.com/Shelex/cypress-allure-plugin-example/blob/master/cypress/e2e/cucumber/examples.feature
> @issue("jira","ACT-222")
> @issue("ACT-111")
> @tms("tms","TC-333")
> @tms("TC-444")
> @link("google","https://google.com")
> @link("https://example.com/")

And it work fine.

However, I see you are trying to use it as decorator in `js` file. And I am not sure it is a supported way to do it for now.

> It was not possible to use @issue or @tms using the last version of this plugin

It was working previously? 🤔

**Comment by Rogatto** [comment]
I'm using directly on the spec. It is strange @tms and @link not working, because the rest of the annotations (allure.epic('Delete product'), allure.feature('Delete product to the cart using API', allure.severity('BLOCKER') are working well.


Code example:

import HomePage from "../../pages/HomePage";
import CartPage from "../../pages/CartPage";

const allure = Cypress.Allure.reporter.getInterface();
allure.epic('Delete product');
allure.feature('Delete product to the cart using API');
allure.severity('BLOCKER');
allure.issue('XRA2NLFQ');
allure.tms('XRA2NLFQ');


describe('delete product to the cart using API to add products to cart', { tags: ['smoke'] }, () => {
    
    Cypress._.times(3, (k) => {
        it(`clicking to the delete button on cart page using API to add product ${k + 1} / 1`, () => {
            cy.api_addProductToCart("4",1)
            cy.visit("/cart")
    
            HomePage.deleteProductToTheCart()
            CartPage.elements.successfullyDeletedProductMessageElement()
            .should('be.visible')
            .contains("Successfully deleted product from cart!")

            cy.screenshot();
        })
    })
});

dev dependencies used:

"devDependencies": {
    "@shelex/cypress-allure-plugin": "^2.31.0",
    "cypress": "^10.9.0",
    "cypress-dark": "^1.8.3",
    "cypress-grep": "^3.0.3",
    "cypress-multi-reporters": "^1.6.1",
    "cypress-xpath": "^2.0.1",
    "mochawesome": "^7.1.3",
    "mochawesome-merge": "^4.2.1",
    "mochawesome-report-generator": "^6.2.0"
  }

**Comment by Shelex** [comment]
Thanks for reply, @Rogatto !

> It is strange `@tms` and `@link` are not working, because the rest of the annotations [...] are working well.

This methods are **not an annotation**. As far as I know, `annotations` do not even exist in JS (however there is similar thing called `decorators`, maybe you mean that, but it is an experimental feature anyway, JS Proposal is in Stage 3 phase since April 2022). 
It is just a way to use allure api in synchronous way.
It works because there is a feature to allow using [label-based](https://github.com/Shelex/allure-js-browser/blob/master/src/model.ts#L106) methods before having tests (e.g. in `beforeEach`) and apply these labels later when test will be started and record in report is created.
It works like that:

1. labels are defined somewhere out of test
2. we do not have test to apply these labels yet
3. we save them
4. when test is finished and received a status, we apply these labels to test
5. when test suite is finished we will re-check if tests are missing labels defined in upper scope, but will not overwrite existing labels.

So your code will work the same way as putting all these sync allure api calls into `beforeEach`:
```
beforeEach(() => {
    const allure = Cypress.Allure.reporter.getInterface();
    allure.epic('Delete product');
    allure.feature('Delete product to the cart using API');
    allure.severity('BLOCKER');
    allure.issue('XRA2NLFQ');
    allure.tms('XRA2NLFQ');
});
```
(but also `issue` and `tms` should work fine, as in beforeEach technically test recording is started)

"label-based" means that `allure.severity('BLOCKER')` is equal to `allure.label('severity', 'BLOCKER')`.

While `tms` and `issue` and shorthands for `link(url, name, LinkType.TMS)` and `link(url, name, LinkType.ISSUE)`

So it seems it is not a bug, but rather a feature request to make `tms` and `issue` be working the same way as labels. The problem is - I hardly imagine a situation when **same** issue link or tms link should be applied to **EACH** test in suite, as per my understanding 1 test is a separate case anyway.

**Comment by Rogatto** [comment]
It worked adding those to the beforeEach, thanks  @Shelex
