### ISSUE TITLE
Deploy Allure report to github action

### ISSUE THREAD

**Issue by fauzisunarya** [Shelex/cypress-allure-plugin#227]
hello, please make a procedure deploy allure report to github action, because i try always failed, please help me

**Comment by Shelex** [comment]
Hi @fauzisunarya 
Thank you for opening an issue.

This plugin responsibility is just gathering information during test execution and saving results.
However, there are multiple examples across github and in this repository as links - https://github.com/Shelex/cypress-allure-plugin?tab=readme-ov-file#examples

Anyway, I see you have a repo [fauzisunarya/report](https://github.com/fauzisunarya/report) with [report](https://fauzisunarya.github.io/report/) being generated and published to github pages, so I am not sure what is the issue here.
