### ISSUE TITLE
Consider integration with cypress-image-snapshot

### ISSUE THREAD

**Issue by kirill-konshin** [Shelex/cypress-allure-plugin#28]
**Is your feature request related to a problem? Please describe.**

Thank you for your awesome library, first of all.

You have a great example how to integrate with cypress-plugin-snapshot: https://github.com/Shelex/cypress-allure-snapshots-example/blob/master/cypress/support/index.js

Unfortunately, it's severely lacking feature, for instance, diffing is not very configurable.

https://github.com/jaredpalmer/cypress-image-snapshot provides a more fine-tuned way to configure diffing.

**Comment by kirill-konshin** [comment]
The issue is that in current shape your plugin seems to attach diffs improperly:

![image](https://user-images.githubusercontent.com/1530410/97769875-9d157d00-1aeb-11eb-86df-e98c5db7d6b8.png)

Note the screenshot with 0 bytes.

It is a result of following JSON:

```json
{
  "attachments": [
    {
      "name": "virtualBackground.spec.js.mp4",
      "type": "video/mp4",
      "source": "/Users/dis/Sites/RCV/rwc/packages/cypress/cypress/videos/virtualBackground.spec.js.mp4"
    },
    {
      "name": "virtualBackground.spec.js:2020-10-31T03:06:00.384Z",
      "type": "image/png",
      "source": "VirtualBackground -- Has virtual background buton when localStorage has the key.diff.png"
    },
  ],
}
```

Note that video was attached properly.

I've made a simple hack:

```js
afterEach(() => {
  const state = Cypress.state();
  if (
    !state.error ||
    !state.error.message.includes("different from saved snapshot")
  ) {
    return;
  }

  const screenshot = regex.exec(state.error.message)[1];

  cy.allure()
    .then(allure =>
      allure.currentTest.addAttachment("screenshot", "image/png", screenshot)
    )
    .then(null, e => cy.log("Cannot save screenshot", e.stack));
});
```

Which you can see in the orig screenshot (line called `screenshot`), and here's the JSON:

```json
  "attachments": [
    {
      "name": "virtualBackground.spec.js.mp4",
      "type": "video/mp4",
      "source": "/Users/dis/Sites/RCV/rwc/packages/cypress/cypress/videos/virtualBackground.spec.js.mp4"
    },
    {
      "name": "virtualBackground.spec.js:2020-10-31T03:06:00.384Z",
      "type": "image/png",
      "source": "VirtualBackground -- Has virtual background buton when localStorage has the key.diff.png"
    },
    {
      "name": "screenshot",
      "type": "image/png",
      "source": "/Users/dis/Sites/RCV/rwc/packages/cypress/cypress/snapshots/virtualBackground.spec.js/__diff_output__/VirtualBackground -- Has virtual background buton when localStorage has the key.diff.png"
    }
  ],
```

So Allure generator properly picks up absolute paths.

Also I noted that on screenshot there's a weird `function (){}` in steps of `matchImageSnapshot`.

Also I noted that `cy.screenshot();` will also result in an empty file...

**Comment by Shelex** [comment]
I guess there is no further action required in terms of this ticket so will shortly address some points that were mentioned here:
 - issue with screenshots is resolved.
- `fileAttachment` command is provided which may help to add screenshots by known path rather than new file with content.
- example repo is updated with `fileAttachment` command plus specific label added which enables allure screenshotDiff plugin - a web component that can show overlay view of actual and expected screenshots as well as their diff image: [example result](https://shelex.github.io/cypress-allure-snapshots-example/allure-report/#testresult/66efc39f2bd7671b). 
 - `matchImageSnapshot` from `cypress-plugin-snapshot` has `function (){}` step due to logging of cypress chainer commands. It could be disabled completely with env variable `"allureLogCypress": false`. Options of better customization of cypress logging into steps may be considered, however it is quite tricky.
  - I see no point in supporting any other plugins (except cucumber-preprocessor) in this reporter as users' could do that on their side if needed and in the way they want it be represented in report. That is the point of using Allure in general - it is just a highly customisable report that you can easily supplement with your own data.
