### ISSUE TITLE
Put videos in allure-results folder

### ISSUE THREAD

**Issue by wasder** [Shelex/cypress-allure-plugin#31]
**Is your feature request related to a problem? Please describe.**
Video attachments refers to absolute folder on your system.
Example:
```
    "attachments": [
        {
            "name": "screens.test.js.mp4",
            "type": "video/mp4",
            "source": "/Users/homeuser/Documents/frontend/cypress/videos/screens.test.js.mp4"
        },
        {
            "name": "screens.test.js:2020-11-11T17:28:24.988Z",
            "type": "image/png",
            "source": "056807c6-4a03-4016-973d-a386005e0d28-attachment.png"
        }
    ],
```

**Describe the solution you'd like**
I need to have self contained allure results to zip it and pass somebody else, because of that videos should be contained in allure-results folder the same way as images already. 
```
    "attachments": [
        {
            "name": "screens.test.js.mp4",
            "type": "video/mp4",
            "source": "screens.test.js.mp4"
        },
        {
            "name": "screens.test.js:2020-11-11T17:28:24.988Z",
            "type": "image/png",
            "source": "056807c6-4a03-4016-973d-a386005e0d28-attachment.png"
        }
    ],
```

**Comment by Shelex** [comment]
For all these time while this issue was opened no new option from cypress provided to track events related to video. Moreover videos may be processing when test finished and browser is shut down. 
So only reliable option is to upgrade to v2.3.6 and set `"videosFolder": "allure-results"` in cypress.json or use your custom 'allureResultsPath'. Then videos will be linked by relative path and be available in results folder or even generated report.
