### ISSUE TITLE
Execution stuck with skipped cucumber scenario and afterEach hook

### ISSUE THREAD

**Issue by isbor** [Shelex/cypress-allure-plugin#53]
**Describe the bug**
The problem is very similar to #51 . If a scenario is skipped in a feature file using tags and there is an afterEach hook tests execution is stuck.
Tests run ok if allure=false.
Tests run ok if there are no afterEach hook.
Tests run ok if there are no skipped tests.
Note that I've updated "@shelex/cypress-allure-plugin" to the latest version and verified that #51 is fixed.

![test-stuck](https://user-images.githubusercontent.com/2804208/108521292-40291700-72d4-11eb-8642-28b38e91d117.png)

**To Reproduce**
1. Clone the repo https://github.com/Shelex/cypress-allure-plugin-example
1.1 Optional: Update version of "@shelex/cypress-allure-plugin" to 2.3.5
2. Tag first scenario in Google.feature with @skip
3. Add additional env to `cy:cucumber:run` script in order to skip a scenario like: `--env allure=true,TAGS='not @skip'`
4. Add afterEach hook in a new file or in any of the existing js files in "cypress/integration/cucumber/news/Google" folder

**Expected behavior**
All tests are executed.

**Environment (please complete the following information):**
- Cypress version:                                6.2.0
- OS:                                                    Linux (Ubuntu)

** Developer Tools Console Output **

**Additional context**

**Comment by Shelex** [comment]
@isbor Thanks for opening an issue. Seems like the issue is from cypress-cucumber-preprocessor feature [hide pending scenarios](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/pull/474) not working with `afterEach` hook and published within scope of v2.4.0.

When I set `cypress-cucumber-preprocessor` to 2.3.1 - it is working fine.

Related issues:
 - [cypress/issues/14867](https://github.com/cypress-io/cypress/issues/14867)
 - [cypress-cucumber-preprocessor/issues/503](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/503)
 - [cypress-cucumber-preprocessor/pull/329](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/pull/329)
 
 Unfortunately, that cannot be addressed from this plugin.
