### ISSUE TITLE
Unable to overwrite suite name with cy.allure().suite()

### ISSUE THREAD

**Issue by Yethal** [Shelex/cypress-allure-plugin#54]
**Describe the bug**
I have a before block in support/index.js that sets per suite configuration. One of the items I need to set is the suite name (Every suite needs to have a prefix added to it). If I try to modify the name by calling cy.allure().suite('NAMEHERE) I get following error:
TypeError: Cannot read property 'addLabel' of null

**To Reproduce**
1. Add before() block in support/index.js
2. Add cy.allure().suite('whatever') inside the block
3. Run tests

**Expected behavior**
Tests pass with no issues, suite names in the report are set to whatever was set in the before block

**Environment (please complete the following information):**
- Cypress version:                                6.5.0
- OS:                                                     Windows

** Developer Tools Console Output **

**Additional context**

**Comment by Shelex** [comment]
Hello @Yethal, thank you for opening an issue.

`suite` command just adds a label to test, and then allure generator gathers tests with same suite label into same suite.
As in before/after hooks there is no `test`, this command cannot be executed. I would suggest using `suite` command in before each/ after each hook as this label should be attached to every test, however, existing name of suite will be attached first.
So I think editing suites names should be done with some cypress/mocha events or directly with `Cypress.Allure.reporter.getInterface().currentSuite.name('whatever')`

Hope this would help.

**Comment by Yethal** [comment]
Okay, I managed to make this work using by calling mocha runner directly, like this:
Cypress.mocha.getRunner().suite.suites[0].title = 'sometitle';

Would it be possible to make the cy.allure().suite() chainer be able to interact with the entire suite? There is a lot of things that are much easier to configure once in global before() block than individually in each suite

**Comment by Shelex** [comment]
> Okay, I managed to make this work using by calling mocha runner directly, like this:
> Cypress.mocha.getRunner().suite.suites[0].title = 'sometitle';
> 
> Would it be possible to make the cy.allure().suite() chainer be able to interact with the entire suite? There is a lot of things that are much easier to configure once in global before() block than individually in each suite

Cool that it is resolved.
As for your request, due to allure specifics we should mutate allureTest from before hook when there are no tests running and their representation in allure don't exist. However, It seems to be doable, for example collect commands in before hook and apply them to each test when it is started (means `created` in Allure). Another option is to rewrite allure-js-commons interface entirely (which is used under the hood), where every operation with allure interface is stored and is executed only when some lifecycle event is emitted or some state reached.
However it may be not so trivial to implement so I would advise to stick to runner semantics: there is no test in before hook, so plugin do not know where to put information provided in that case.
