### ISSUE TITLE
Allure report not working with cucumber typescript

### ISSUE THREAD

**Issue by abhinaba-ghosh** [Shelex/cypress-allure-plugin#6]
Hi, 
Allure reporter is capturing the results in allure-results but not actually producing the report in correct format

Scripts
```js
   "cy:cucumber:open": "cypress open --browser chrome",
    "cy:cucumber:run": "cypress run --env allure=true --browser chrome",
    "allure:report": "npx allure generate reports/allure-results --clean -o allure-report",
    "allure:clear": "rm -r reports/allure-results/ reports/allure-report reports/screenshots || true"
```
in cypress.json

```js
 "env": {
    "allureResultsPath": "reports/allure-results"
  }

```

My plugin/index.js
```js
const cucumber = require('cypress-cucumber-preprocessor').default;
const browserify = require('@cypress/browserify-preprocessor');
const allureWriter = require('@shelex/cypress-allure-plugin/writer');


module.exports = (on, config) => {
  const options = browserify.defaultOptions;

  options.browserifyOptions.plugin.unshift(['tsify']);

  on('file:preprocessor', cucumber(options));
  allureWriter(on, config);
  return config;
};

```
![Screenshot 2020-05-14 at 11 01 00 PM](https://user-images.githubusercontent.com/23141842/81966717-82cc0d80-9637-11ea-8f95-32a15f598a37.png)

**Comment by Shelex** [comment]
Hello @abhinaba-ghosh !
Thank you for posting an issue.

I have checked repository [cypress-cucumber-typescript-starter](https://github.com/abhinaba-ghosh/cypress-cucumber-typescript-starter) and it is working as expected.
It seems that you have opened Allure report index.html file instead of running allure web server to serve report page

Here are all steps required:

- `npm i`

- `cypress run --env allure=true --browser chrome`

- `npm run allure:report`

- In order to open report: `allure open reports/allure-report`

And you will see valid report page.
Feel free to check example repo with detailed steps: [cypress-allure-plugin-example](https://github.com/Shelex/cypress-allure-plugin-example#how-to-run)

**Comment by abhinaba-ghosh** [comment]
Thanks thats solves the issue.
