### ISSUE TITLE
folder allure-results dont create

### ISSUE THREAD

**Issue by RuslanAisin** [Shelex/cypress-allure-plugin#83]
Hello,
I am trying to use this plugin. But allure-results doesnt created
my command is npm run cypress-open
in cypress.json
 "env": {
        "allure": true,
        "allureResultsPath": "allure-results"
}
in support\index.js
import '@shelex/cypress-allure-plugin';

in plugins\index.js
 const allureWriter = require('@shelex/cypress-allure-plugin/writer');

 module.exports = (on, config) => {
     allureWriter(on, config);
     return config;
 };

in package.json
"devDependencies": {
    "@shelex/cypress-allure-plugin": "^2.8.3",
    "allure-commandline": "^2.13.8"
}
node v14
cypress 7.6.0
![image](https://user-images.githubusercontent.com/49075028/123958437-bc83e300-d9b5-11eb-8ef0-54bb61d9a7cd.png)

**Comment by RuslanAisin** [comment]
I notice that VScode mark a problem in plugins
![image](https://user-images.githubusercontent.com/49075028/123959415-cf4ae780-d9b6-11eb-94b6-19c667a1eeaf.png)
maybe it my cause?

**Comment by Shelex** [comment]
Hi @RuslanAisin .
Thank you for opening issue.

Issue with VS Code is due to missing type declarations for writer function, that is just for autocompletion purpose and it tells that it will have `any` type. That could be resolved by adding type declarations, but unfortunately is not a source of issue.

Error says that task was not even registered from your plugins. Maybe it is conflicting with something else. Will also check if cypress has not changed anything in v7.6.0.

**Comment by RuslanAisin** [comment]
thank for quick response.
I have changed cypress version to 6.4.0 and 7.4.0 the same problem, I dont know what to do

**Comment by Shelex** [comment]
@RuslanAisin Please contact me by email mentioned in my profile so we can arrange a call to investigate your specific case.

**Comment by Shelex** [comment]
Discussed on a call and it seems that issue is with getting allure-results folder from docker to teamcity agent. Could be resolved by using current folder as a volume mounted in container.
Closing as it is not related to plugin.
